apiVersion: kmm.sigs.x-k8s.io/v1beta1
kind: Module
metadata:
  name: kmodname # kpt-set: ${kmod-name}
  namespace: kmm-operator-system
spec:
  imageRepoSecret:
    name: quay-dockerhub-secret # kpt-set: ${quay-dockerhub-secret}
  moduleLoader:
    container:
      kernelMappings:
        - regexp: ".*"
          containerImage: registry/username/repository:tag # kpt-set: ${container-image}
          build:
            buildArgs:
              - name: SOURCE_URL
                value: source-url # kpt-set: ${source-url}
              # GitHub's tarballs are typically named using the following convention:
              # [repository-name]-[tag-name-without-leading-v]
              # Repository Name: gtp5g
              # Tag Name: v0.8.8
              #  Directory Name: gtp5g-0.8.8
              - name: SOURCE_DIR
                value: source-dir # kpt-set: ${source-dir}
              - name: MODULE_NAME
                value: kmodname # kpt-set: ${kmod-name}
              - name: KERNEL_VERSION
                value: kernel-version # kpt-set: ${kernel-version}
              - name: GCC_PKG
                value: gcc-pkg # kpt-set: ${gcc-pkg}
            dockerfileConfigMap:
              name: kmodname-containerfile # kpt-set: ${kmod-name}-containerfile
      modprobe:
        moduleName: kmodname # kpt-set: ${kmod-name}
  selector:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64